FROM node:18

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

# nodemonをグローバルインストール（もしくはdevDependenciesに含めておく）
RUN npm install -g nodemon

EXPOSE 5001

CMD ["nodemon", "server/server.js"]